WMS.Api/ViewModels/UserSecretKeyViewModels/ShowUserSecretKeyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WMS.Api.ViewModels.UserSecretKeyViewModels
{
    public class ShowUserSecretKeyViewModel
    {
        public Guid ApplicationId { get; set; }
        public string ApplicationName { get; set; }
        public string SecretKey { get; set; }
    }
}

WMS.Api/Controllers/UserSecretKeyController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WMS.Api.Services;
using Microsoft.AspNet.Identity;
using WMS.Api.ViewModels.UserSecretKeyViewModels;
using WMS.Api.ViewModels.ApiClientViewModels;
using WMS.Api.DAL.Models.ApiAuthModels;
using WMS.Api.DAL.DatabaseContext;
using System.Linq;

namespace WMS.Api.Controllers
{
    [Authorize]
    public class UserSecretKeyController : Controller
    {
        private ApiClientService _apiClientService;
        private UserSecretKeyService _userSecretKeyService;

        public UserSecretKeyController()
        {
            _apiClientService = new ApiClientService();
            _userSecretKeyService = new UserSecretKeyService();
        }

        public ActionResult Index()
        {
            var apiClients = _apiClientService.GetAllApiClientsNames().ToList();
            return View(apiClients);
        }

        public ActionResult ShowUserSecretKey(Guid apiClientId)
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());
            var userSecretKey = _userSecretKeyService.GetUserSecretKey(userId, apiClientId);            
            return View(userSecretKey);
        }
        
        public ActionResult CreateUserSecretKey(ShowUserSecretKeyViewModel showUserSecretKeyVM)
        {
            if (ModelState.IsValid)
            {
                Guid userId = Guid.Parse(User.Identity.GetUserId());
                var userSecretKey = _userSecretKeyService.GenerateUserSecretKey(userId, showUserSecretKeyVM.ApplicationId);
                showUserSecretKeyVM.SecretKey = userSecretKey;
                return View("ShowUserSecretKey", showUserSecretKeyVM);
            }
            return RedirectToAction("index");
        }
    }
}

WMS.Api/Views/UserSecretKey/Index.cshtml
@model IEnumerable<WMS.Api.ViewModels.ApiClientViewModels.ShowAllApiClientNameViewModel>

@{
    ViewBag.Title = "Index";
}

@if (Model.Count() > 0)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Show key for login", "ShowUserSecretKey", "UserSecretKey",new { apiClientId = item.Id }, new { @class="btn btn-default" })
                </td>
            </tr>
        }

    </table>
}
else
{
    <h1>There is no API clients.</h1>
}

WMS.Api/Views/UserSecretKey/ShowUserSecretKey.cshtml
@model WMS.Api.ViewModels.UserSecretKeyViewModels.ShowUserSecretKeyViewModel

@{
    ViewBag.Title = "ShowUserSecretKey";
}
 
<h2>ShowUserSecretKey</h2>

@if (!Model.SecretKey.IsEmpty())
{
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ApplicationName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ApplicationName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SecretKey)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SecretKey)
            </dd>

        </dl>
    </div>

    @Html.ActionLink("Generate new key", "CreateUserSecretKey", "UserSecretKey", Model, new { @class = "btn btn-default" })
}
else
{
    <h1>No key has been generated yet!</h1>
    @Html.ActionLink("Generate key", "CreateUserSecretKey", "UserSecretKey", Model, new { @class = "btn btn-default" })
}